# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookWorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
