# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookWorm', '0002_book_readdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='bookWorm/static/images'),
        ),
    ]
