# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookWorm', '0003_book_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
