# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookWorm', '0004_auto_20170221_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coverImage',
        ),
    ]
